name: klipy_flutter
version: 0.0.1
description: An opinionated yet customizable Flutter package for searching and selecting from a list of GIFs/Stickers from the KLIPY GIF search API.
homepage: https://github.com/flyclops
repository: https://github.com/flyclops/klipy_flutter
topics:
  - gif
  - tenor

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  flutter_staggered_grid_view: ^0.7.0
  extended_image: ^10.0.1
  klipy_dart:
    path: ../klipy_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/
